/* 
 * File:   mcal_interrupt_cfg.h
 * Author: FiX-DEll
 *
 * Created on March 9, 2024, 12:03 AM
 */

#ifndef MCAL_INTERRUPT_CFG_H
#define	MCAL_INTERRUPT_CFG_H

#define INTERRUPT_FEATURE_ENABLE 1
#define TIMER1_INTERRUPT_FEATURE_ENABLE       INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_FEATURE_ENABLE         INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE         INTERRUPT_FEATURE_ENABLE

#endif	/* MCAL_INTERRUPT_CFG_H */

